CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings -Weffc++

main: TPa.cpp
	echo     ------------compiling TPa.ccp to create executable program TPa----------------
	g++ -ggdb -std=c++11 TPa.cpp -o TPa

clean:
	echo ----------------removing executable program TPa--------------------
	/bin/rm TPa
