CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings -Weffc++

main: tp0_tpf_test.cpp
	echo     ------------compiling tp0_tpf_test.ccp to create executable program tp0_tpf_test----------------
	g++ -ggdb -std=c++11 tp0_tpf_test.cpp -o tp0_tpf_test

clean:
	echo ----------------removing executable program tp0_tpf_test--------------------
	/bin/rm tp0_tpf_test
