CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings -Weffc++

main: TPf.cpp
	echo     ------------compiling TPf.ccp to create executable program TPf----------------
	g++ -ggdb -std=c++11 TPf.cpp -o TPf

clean:
	echo ----------------removing executable program TPf--------------------
	/bin/rm TPf
