CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings -Weffc++

main: TP0.cpp
	echo     ------------compiling TP0.ccp to create executable program TP0----------------
	g++ -ggdb -std=c++11 TP0.cpp -o TP0

clean:
	echo ----------------removing executable program TP0--------------------
	/bin/rm TP0
