CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant -Weffc++
CFLAGS=-std=c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings -Weffc++

main: BST.cpp
	echo     ------------compiling BST.ccp to create executable program BST----------------
	g++ -ggdb -std=c++11 BST.cpp -o BST

clean:
	echo ----------------removing executable program BST--------------------
	/bin/rm BST
